version: 0.2

phases:
  install:
    commands:
      - Set-Service -Name wuauserv -StartupType Manual
      - DISM /Online /Enable-Feature:NetFx3 /All /Quiet
      - choco install -y wixtoolset --version 3.11.0.20170506 --no-progress
      # install .NET SDK and runtimes
      - choco install dotnet-sdk --version 6.0.415 -y --no-progress
  pre_build:
    commands:
      - mkdir c:\temp
      - mkdir c:\temp\bookmark
      - mkdir signed_artifacts
      - $input_artifacts = (Get-ChildItem Env:CODEBUILD_SRC_DIR_BuildOutput_artifacts).Value
      - Get-ChildItem $input_artifacts -Recurse -filter *.dll | Copy-Item -Destination signed_artifacts
      - Get-ChildItem $input_artifacts -Recurse -filter *.exe | Copy-Item -Destination signed_artifacts
  build:
    commands:
      - dotnet --info
      - dotnet restore AWSKinesisTap.sln
      - nuget restore .\KinesisTapMsiBuild.sln
      - dotnet build AWSKinesisTap.sln -c Release
      - dotnet test .\AWSKinesisTap.sln -c Release --filter Category!=Integration
  post_build:
    commands:
      - .\build.ps1
artifacts:
  files:
    - Amazon.KinesisTap/bin/*.msi
    - Amazon.KinesisTap/bin/*.nupkg
    - Amazon.KinesisTap.Deploy/*
    - Amazon.KinesisTap/Birdwatcher/bin/*.zip
    - Amazon.KinesisTap.CiIntegration.Test/bin/release/*.zip